### ISSUE TITLE
is this project can work?

### ISSUE THREAD

**Issue by toidibin** [cameronws/VideoTest#1]
could you tell me how to use the videoeditor plugin ,the function of transcodeVideo  has any callback result.  Should you have any suggestions, please advise.thks

**Comment by cameronws** [comment]
1stly, this is a testing app that I'm using for another project and shouldn't (wouldn't recommend it) be used for any production/real world apps.

2ndly, there is a callback function for success as well as error when attempting to trans-code a video. The issue with trans-coding is that the process takes a long time depending on the length of the video you want to trans-code, e.g: trimming a video to 12 seconds on "high" quality takes around 2 minutes.

The result of the success callback is the path to the trans-coded video, whereas the result of the error callback is the error generated within the plugin: https://github.com/jbavari/cordova-plugin-video-editor.

**Comment by toidibin** [comment]
I use the plugin :https://github.com/jbavari/cordova-plugin-video-editor  and it works . thank you for your help.
